// Copyright 2026 Qwentrix Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package report renders the local HTML risk report from a scoring payload.
//
// ENT-106 implementation: the output is a single, fully self-contained HTML file.
//
//   - All CSS is inlined from the embedded style.css (go:embed in template.go).
//   - Charts are inline SVG, generated by chart_svg.go — no JS, no CDN.
//   - The report renders the FULL ReportPayload: overall score and grade,
//     per-domain scores and grades, the "Why?" explainability trace
//     (ExplainStep contributions), a "What to fix first" section ordered by
//     contribution with Micelium product alignment indicators, fired findings
//     with framework citations, and plain remediation text.
//
// Self-contained gate:
//
//	Render() calls renderHTML() which, after template execution, asserts that the
//	output contains ZERO http:// or https:// substrings and returns an error if
//	the gate fails. This prevents a template edit from accidentally introducing a
//	CDN or remote-font reference that would break offline / air-gapped use.
//	The CI test in report_selfcontained_test.go is the primary gate; this runtime
//	check is a defense-in-depth secondary layer.
//
// Print-friendly: the embedded style.css includes a @media print block that
// disables box-shadows and applies page-break-inside: avoid on finding cards,
// so the HTML can be saved as PDF with a single File > Print command.
package report

import (
	"fmt"
	"os"

	lstypes "github.com/Qwentrix/lumen-scoring/pkg/types"
)

// Render writes a self-contained HTML report to outputPath.
//
// The payload is the result of scoring.ScoreScan(). Render delegates to
// renderHTML (html_renderer.go) which executes the embedded template and
// applies the self-contained gate before returning the HTML string.
//
// The output file is created with mode 0644 (world-readable, which is normal
// for a report file in the user's home directory).
func Render(payload *lstypes.ReportPayload, outputPath string) error {
	html, err := renderHTML(payload)
	if err != nil {
		return err
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create report file: %w", err)
	}
	defer f.Close()

	_, err = f.WriteString(html)
	return err
}
